version: "3"
services:
  products-svc:
    image: devops/products-service:latest
    container_name: products-service
    ports:
      - "8181:8080"
    networks:
      - net
  payments-svc:
    image: devops/payments-service:latest
    container_name: payments-service
    ports:
      - "8182:8080"
    networks:
      - net
  shipping-svc:
    image: devops/shipping-service:latest
    container_name: shipping-service
    ports:
      - "8183:8080"
    networks:
      - net
  orders-svc:
    image: devops/orders-service:latest
    container_name: orders-service
    environment:
      - APP_ARGS=http://payments-service:8080 http://shipping-service:8080 http://products-service:8080
    ports:
      - "8180:8080"
    networks:
      - net
networks:
  net:
